variables:
  GIT_SUBMODULE_STRATEGY: recursive

lassen-build:
    tags:
      - lassen
    script:
      - module load cuda/11 # 11.0.2 ... 11.2.0
      - module load gcc/7
      - export CUDAFLAGS="--gpu-architecture sm_70"
      - pwd      
