# Use cibuildwheel v2 to build wheels for Python 3.
# Based on https://cibuildwheel.readthedocs.io/en/stable/setup/

name: Wheels2

on:
  workflow_dispatch:
    inputs:
      cibw_build:
        description: 'CIBW_BUILD'
        default: '*'
      cibw_skip:
        description: 'CIBW_SKIP'
        # To limit the number of builds, skip most of musl-based versions,
        # older PyPy versions, and 32-bit builds.
        default: 'pp{37,38}-* cp{36,37,38}-musllinux* *_i686 *-win32'

env:
  CIBW_TEST_COMMAND: python -m unittest discover -v -s {project}/tests/

jobs:
  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
    - uses: actions/checkout@v3

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.12.3
      env:
        CIBW_BUILD: ${{ github.event.inputs.cibw_build }}
        CIBW_SKIP: ${{ github.event.inputs.cibw_skip }}
        CIBW_ARCHS_MACOS: x86_64 arm64
        # increase pip debugging output
        CIBW_BUILD_VERBOSITY: 1

    - run: ls -lh wheelhouse
      shell: bash

    - uses: actions/upload-artifact@v3
      with:
        name: wheels2
        path: wheelhouse/*.whl
