# Use cibuildwheel v1 to build wheels for Python 2.7.
# Based on https://cibuildwheel.readthedocs.io/en/1.x/setup/
name: Wheels

on:
  workflow_dispatch:
    inputs:
      cibw_build:
        description: 'CIBW_BUILD'
        # Python 3 is built in wheels2.yml.
        default: 'cp27-*'
      cibw_skip:
        description: 'CIBW_SKIP'
        # Python 2.7 on Windows requires a workaround for C++11 support,
        # To limit the number of builds, skip 32-bit builds.
        default: 'cp27-win* *linux_i686'

env:
  CIBW_TEST_COMMAND: python -m unittest discover -v -s {project}/tests/

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Install deps
      run: python -m pip install twine build

    - name: Build SDist
      run: python -m build -s

    - name: Check metadata
      run: twine check dist/*

    - uses: actions/upload-artifact@v2
      with:
        name: sdist
        path: dist/*.tar.gz


  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # don't include windows-2019, we skip Python2.7 for Windows
        os: [ubuntu-20.04, macos-10.15]

    steps:
    - uses: actions/checkout@v2

    - uses: pypa/cibuildwheel@v1.12.0
      env:
        CIBW_BUILD: ${{ github.event.inputs.cibw_build }}
        CIBW_SKIP: ${{ github.event.inputs.cibw_skip }}
        # increase pip debugging output
        CIBW_BUILD_VERBOSITY: 1

    - run: ls -lh wheelhouse
      shell: bash

    - uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: wheelhouse/*.whl
